/********************************************************************************
** Form generated from reading UI file 'MainWindow.ui'
**
** Created: Wed Nov 16 15:23:24 2011
**      by: Qt User Interface Compiler version 4.7.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QDoubleSpinBox>
#include <QtGui/QFrame>
#include <QtGui/QGridLayout>
#include <QtGui/QGroupBox>
#include <QtGui/QHBoxLayout>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QRadioButton>
#include <QtGui/QSpinBox>
#include <QtGui/QSplitter>
#include <QtGui/QStatusBar>
#include <QtGui/QToolBox>
#include <QtGui/QVBoxLayout>
#include <QtGui/QWidget>
#include "QVTKWidget.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *DcmToMhd;
    QAction *MorpherVolumeCdbToVtk;
    QAction *PointsStlToTxt;
    QAction *MorpherVolumeCdbToVtk_2;
    QAction *MorpherSurfaceCdbToStl_2;
    QAction *RenderStl;
    QAction *RenderVolumeCdb;
    QAction *RenderMetafile;
    QAction *InpToCdb;
    QAction *RenderSurfaceCdb;
    QAction *RenderVolumeVtk;
    QAction *RenderSurfaceVtk;
    QAction *PointsVtkToTxt;
    QAction *MhdToHdr;
    QAction *CdbToInpAbaqus;
    QAction *RenderVolumeInpAbaqus;
    QAction *PointsTxtMatrixToVector;
    QAction *ResetView;
    QAction *RenderCoordinateSystem;
    QAction *MhdToDcm;
    QAction *AbaqusToCdb;
    QAction *RenderVtkPolyData;
    QAction *RenderOBB;
    QAction *RenderPointsXyz;
    QAction *RenderPointsXyzWithColorbar;
    QAction *DistancePoints;
    QAction *EuclideanDistanceImage;
    QAction *EuclideanDistancePoints;
    QAction *RenderPointsXyzWithColorbarC;
    QAction *DrawLineStart;
    QAction *DrawLineStop;
    QAction *RenderLine;
    QWidget *centralwidget;
    QGridLayout *gridLayout_2;
    QGroupBox *groupBox_31;
    QGridLayout *gridLayout;
    QSplitter *splitter;
    QToolBox *toolBox;
    QWidget *page_1;
    QGroupBox *groupBox;
    QGroupBox *groupBox_15;
    QPushButton *RecreateImageInstance;
    QGroupBox *groupBox_17;
    QRadioButton *ShapeImagePCA;
    QRadioButton *CombinedImagePCA;
    QRadioButton *IntensityImagePCA;
    QPushButton *CalculateImagePCA;
    QGroupBox *groupBox_23;
    QSpinBox *NOfImageInstances;
    QLabel *label_11;
    QLabel *label_14;
    QSpinBox *NOfImageModes_2;
    QPushButton *CreateImageInstances;
    QGroupBox *groupBox_3;
    QWidget *layoutWidget;
    QVBoxLayout *verticalLayout_2;
    QPushButton *MaskGreyLevel;
    QPushButton *MaskImage;
    QPushButton *BinaryMaskDcm;
    QWidget *layoutWidget1;
    QVBoxLayout *verticalLayout;
    QPushButton *ImageResample;
    QPushButton *ItkToVtkToItk;
    QPushButton *PseudoCalibration;
    QGroupBox *groupBox_8;
    QPushButton *FindReference;
    QGroupBox *groupBox_18;
    QPushButton *SurfaceComparisonImage;
    QPushButton *VolumeComparisonImage;
    QGroupBox *groupBox_19;
    QPushButton *VfToDvf;
    QPushButton *RecreateMoving;
    QPushButton *VfToDvfInverted;
    QFrame *line_2;
    QPushButton *RecreateReference;
    QWidget *page_2;
    QGroupBox *groupBox_6;
    QGroupBox *groupBox_11;
    QPushButton *CreateMesh;
    QDoubleSpinBox *Simplify;
    QSpinBox *Smooth;
    QLabel *label;
    QPushButton *LoadImageMesh;
    QLabel *label_2;
    QGroupBox *groupBox_13;
    QPushButton *CreateVolumeMesh;
    QPushButton *LoadSurfaceMesh;
    QGroupBox *groupBox_26;
    QWidget *layoutWidget2;
    QHBoxLayout *horizontalLayout;
    QPushButton *MeshJacobian;
    QPushButton *MeshEdgeRatio;
    QPushButton *MeshAngle;
    QGroupBox *groupBox_7;
    QGroupBox *groupBox_12;
    QPushButton *CreateXml;
    QPushButton *PickLandmarks;
    QPushButton *CreateXmlFromFiles;
    QFrame *line;
    QGroupBox *groupBox_27;
    QPushButton *RunMorpher;
    QGroupBox *groupBox_14;
    QPushButton *SurfaceValidation;
    QPushButton *VolumeValidation;
    QGroupBox *groupBox_2;
    QGroupBox *groupBox_4;
    QPushButton *CalculateMeshPCA;
    QRadioButton *ShapeMeshPCA;
    QRadioButton *CombinedMeshPCA;
    QRadioButton *IntensityMeshPCA;
    QGroupBox *groupBox_24;
    QLabel *label_12;
    QSpinBox *NOfMeshInstances;
    QPushButton *CreateMeshInstances;
    QLabel *label_13;
    QSpinBox *NOfMeshModes;
    QGroupBox *groupBox_9;
    QPushButton *RecreateMeshInstance;
    QGroupBox *groupBox_25;
    QPushButton *MeshAlignment;
    QPushButton *ExtractCoordinatesAndIntensities;
    QPushButton *ExtractNodesAndElements;
    QWidget *page_3;
    QGroupBox *groupBox_16;
    QPushButton *LoadMesh;
    QPushButton *LoadImageAssigner;
    QLabel *label_4;
    QDoubleSpinBox *AssignmentLawFirst;
    QLabel *label_6;
    QLabel *label_7;
    QDoubleSpinBox *AssignmentLawSecond;
    QPushButton *Assign;
    QLabel *label_3;
    QGroupBox *groupBox_20;
    QRadioButton *AssignToNodes;
    QRadioButton *AssignToElements;
    QGroupBox *groupBox_21;
    QRadioButton *AbaqusMatProp;
    QRadioButton *TxtMatProp;
    QGroupBox *groupBox_5;
    QGroupBox *groupBox_29;
    QPushButton *Falling;
    QPushButton *Walking;
    QGroupBox *groupBox_28;
    QFrame *line_3;
    QPushButton *PickApplicationPoints;
    QPushButton *SaveApplicationPoints;
    QPushButton *PropagateApplicationPoints;
    QGroupBox *groupBox_10;
    QPushButton *RunSimulation;
    QFrame *line_4;
    QPushButton *CreateAbaqusInpFalling;
    QPushButton *CreateAbaqusInp;
    QGroupBox *groupBox_22;
    QPushButton *LoadBoneMesh;
    QPushButton *LoadImplantMesh;
    QPushButton *ComputeAndSave;
    QRadioButton *Proximal;
    QRadioButton *Diaphyseal;
    QRadioButton *Distal;
    QGroupBox *groupBox_30;
    QPushButton *ExtractNeckIntensities;
    QVTKWidget *qvtkWidget;
    QMenuBar *menubar;
    QMenu *menu_Rendering;
    QMenu *menuMesh;
    QMenu *menuSurface_mesh;
    QMenu *menuVolume_Mesh;
    QMenu *menuImage;
    QMenu *menuPoints_2;
    QMenu *menuDifference;
    QMenu *menuEuclidean;
    QMenu *menu_Change_format;
    QMenu *menuImages;
    QMenu *menuMesh_2;
    QMenu *menuVolume_Mesh_2;
    QMenu *menuSurfaceMesh;
    QMenu *menuPoints;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1271, 798);
        DcmToMhd = new QAction(MainWindow);
        DcmToMhd->setObjectName(QString::fromUtf8("DcmToMhd"));
        MorpherVolumeCdbToVtk = new QAction(MainWindow);
        MorpherVolumeCdbToVtk->setObjectName(QString::fromUtf8("MorpherVolumeCdbToVtk"));
        PointsStlToTxt = new QAction(MainWindow);
        PointsStlToTxt->setObjectName(QString::fromUtf8("PointsStlToTxt"));
        MorpherVolumeCdbToVtk_2 = new QAction(MainWindow);
        MorpherVolumeCdbToVtk_2->setObjectName(QString::fromUtf8("MorpherVolumeCdbToVtk_2"));
        MorpherSurfaceCdbToStl_2 = new QAction(MainWindow);
        MorpherSurfaceCdbToStl_2->setObjectName(QString::fromUtf8("MorpherSurfaceCdbToStl_2"));
        RenderStl = new QAction(MainWindow);
        RenderStl->setObjectName(QString::fromUtf8("RenderStl"));
        RenderVolumeCdb = new QAction(MainWindow);
        RenderVolumeCdb->setObjectName(QString::fromUtf8("RenderVolumeCdb"));
        RenderMetafile = new QAction(MainWindow);
        RenderMetafile->setObjectName(QString::fromUtf8("RenderMetafile"));
        InpToCdb = new QAction(MainWindow);
        InpToCdb->setObjectName(QString::fromUtf8("InpToCdb"));
        RenderSurfaceCdb = new QAction(MainWindow);
        RenderSurfaceCdb->setObjectName(QString::fromUtf8("RenderSurfaceCdb"));
        RenderVolumeVtk = new QAction(MainWindow);
        RenderVolumeVtk->setObjectName(QString::fromUtf8("RenderVolumeVtk"));
        RenderSurfaceVtk = new QAction(MainWindow);
        RenderSurfaceVtk->setObjectName(QString::fromUtf8("RenderSurfaceVtk"));
        PointsVtkToTxt = new QAction(MainWindow);
        PointsVtkToTxt->setObjectName(QString::fromUtf8("PointsVtkToTxt"));
        MhdToHdr = new QAction(MainWindow);
        MhdToHdr->setObjectName(QString::fromUtf8("MhdToHdr"));
        CdbToInpAbaqus = new QAction(MainWindow);
        CdbToInpAbaqus->setObjectName(QString::fromUtf8("CdbToInpAbaqus"));
        RenderVolumeInpAbaqus = new QAction(MainWindow);
        RenderVolumeInpAbaqus->setObjectName(QString::fromUtf8("RenderVolumeInpAbaqus"));
        PointsTxtMatrixToVector = new QAction(MainWindow);
        PointsTxtMatrixToVector->setObjectName(QString::fromUtf8("PointsTxtMatrixToVector"));
        ResetView = new QAction(MainWindow);
        ResetView->setObjectName(QString::fromUtf8("ResetView"));
        RenderCoordinateSystem = new QAction(MainWindow);
        RenderCoordinateSystem->setObjectName(QString::fromUtf8("RenderCoordinateSystem"));
        MhdToDcm = new QAction(MainWindow);
        MhdToDcm->setObjectName(QString::fromUtf8("MhdToDcm"));
        AbaqusToCdb = new QAction(MainWindow);
        AbaqusToCdb->setObjectName(QString::fromUtf8("AbaqusToCdb"));
        RenderVtkPolyData = new QAction(MainWindow);
        RenderVtkPolyData->setObjectName(QString::fromUtf8("RenderVtkPolyData"));
        RenderOBB = new QAction(MainWindow);
        RenderOBB->setObjectName(QString::fromUtf8("RenderOBB"));
        RenderPointsXyz = new QAction(MainWindow);
        RenderPointsXyz->setObjectName(QString::fromUtf8("RenderPointsXyz"));
        RenderPointsXyzWithColorbar = new QAction(MainWindow);
        RenderPointsXyzWithColorbar->setObjectName(QString::fromUtf8("RenderPointsXyzWithColorbar"));
        DistancePoints = new QAction(MainWindow);
        DistancePoints->setObjectName(QString::fromUtf8("DistancePoints"));
        EuclideanDistanceImage = new QAction(MainWindow);
        EuclideanDistanceImage->setObjectName(QString::fromUtf8("EuclideanDistanceImage"));
        EuclideanDistancePoints = new QAction(MainWindow);
        EuclideanDistancePoints->setObjectName(QString::fromUtf8("EuclideanDistancePoints"));
        RenderPointsXyzWithColorbarC = new QAction(MainWindow);
        RenderPointsXyzWithColorbarC->setObjectName(QString::fromUtf8("RenderPointsXyzWithColorbarC"));
        DrawLineStart = new QAction(MainWindow);
        DrawLineStart->setObjectName(QString::fromUtf8("DrawLineStart"));
        DrawLineStop = new QAction(MainWindow);
        DrawLineStop->setObjectName(QString::fromUtf8("DrawLineStop"));
        RenderLine = new QAction(MainWindow);
        RenderLine->setObjectName(QString::fromUtf8("RenderLine"));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        gridLayout_2 = new QGridLayout(centralwidget);
        gridLayout_2->setObjectName(QString::fromUtf8("gridLayout_2"));
        groupBox_31 = new QGroupBox(centralwidget);
        groupBox_31->setObjectName(QString::fromUtf8("groupBox_31"));
        gridLayout = new QGridLayout(groupBox_31);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        splitter = new QSplitter(groupBox_31);
        splitter->setObjectName(QString::fromUtf8("splitter"));
        splitter->setOrientation(Qt::Horizontal);
        toolBox = new QToolBox(splitter);
        toolBox->setObjectName(QString::fromUtf8("toolBox"));
        QSizePolicy sizePolicy(QSizePolicy::Minimum, QSizePolicy::Minimum);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(toolBox->sizePolicy().hasHeightForWidth());
        toolBox->setSizePolicy(sizePolicy);
        toolBox->setMaximumSize(QSize(375, 16777215));
        QFont font;
        font.setFamily(QString::fromUtf8("Segoe UI"));
        font.setPointSize(11);
        toolBox->setFont(font);
        toolBox->setLayoutDirection(Qt::LeftToRight);
        page_1 = new QWidget();
        page_1->setObjectName(QString::fromUtf8("page_1"));
        page_1->setGeometry(QRect(0, 0, 375, 617));
        groupBox = new QGroupBox(page_1);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(10, 330, 351, 251));
        QFont font1;
        font1.setPointSize(9);
        groupBox->setFont(font1);
        groupBox_15 = new QGroupBox(groupBox);
        groupBox_15->setObjectName(QString::fromUtf8("groupBox_15"));
        groupBox_15->setGeometry(QRect(10, 100, 331, 51));
        RecreateImageInstance = new QPushButton(groupBox_15);
        RecreateImageInstance->setObjectName(QString::fromUtf8("RecreateImageInstance"));
        RecreateImageInstance->setGeometry(QRect(10, 20, 311, 23));
        RecreateImageInstance->setFont(font1);
        groupBox_17 = new QGroupBox(groupBox);
        groupBox_17->setObjectName(QString::fromUtf8("groupBox_17"));
        groupBox_17->setGeometry(QRect(10, 20, 331, 71));
        ShapeImagePCA = new QRadioButton(groupBox_17);
        ShapeImagePCA->setObjectName(QString::fromUtf8("ShapeImagePCA"));
        ShapeImagePCA->setGeometry(QRect(11, 21, 83, 18));
        CombinedImagePCA = new QRadioButton(groupBox_17);
        CombinedImagePCA->setObjectName(QString::fromUtf8("CombinedImagePCA"));
        CombinedImagePCA->setGeometry(QRect(217, 21, 103, 18));
        IntensityImagePCA = new QRadioButton(groupBox_17);
        IntensityImagePCA->setObjectName(QString::fromUtf8("IntensityImagePCA"));
        IntensityImagePCA->setGeometry(QRect(114, 21, 97, 18));
        CalculateImagePCA = new QPushButton(groupBox_17);
        CalculateImagePCA->setObjectName(QString::fromUtf8("CalculateImagePCA"));
        CalculateImagePCA->setGeometry(QRect(10, 40, 311, 23));
        groupBox_23 = new QGroupBox(groupBox);
        groupBox_23->setObjectName(QString::fromUtf8("groupBox_23"));
        groupBox_23->setGeometry(QRect(10, 160, 331, 81));
        NOfImageInstances = new QSpinBox(groupBox_23);
        NOfImageInstances->setObjectName(QString::fromUtf8("NOfImageInstances"));
        NOfImageInstances->setGeometry(QRect(100, 21, 51, 20));
        NOfImageInstances->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        NOfImageInstances->setMaximum(2000);
        label_11 = new QLabel(groupBox_23);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(12, 21, 80, 16));
        label_14 = new QLabel(groupBox_23);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(170, 21, 66, 16));
        NOfImageModes_2 = new QSpinBox(groupBox_23);
        NOfImageModes_2->setObjectName(QString::fromUtf8("NOfImageModes_2"));
        NOfImageModes_2->setGeometry(QRect(270, 21, 51, 20));
        NOfImageModes_2->setMaximum(200);
        CreateImageInstances = new QPushButton(groupBox_23);
        CreateImageInstances->setObjectName(QString::fromUtf8("CreateImageInstances"));
        CreateImageInstances->setGeometry(QRect(10, 50, 311, 23));
        groupBox_3 = new QGroupBox(page_1);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 0, 351, 111));
        groupBox_3->setFont(font1);
        layoutWidget = new QWidget(groupBox_3);
        layoutWidget->setObjectName(QString::fromUtf8("layoutWidget"));
        layoutWidget->setGeometry(QRect(180, 20, 161, 83));
        verticalLayout_2 = new QVBoxLayout(layoutWidget);
        verticalLayout_2->setObjectName(QString::fromUtf8("verticalLayout_2"));
        verticalLayout_2->setContentsMargins(0, 0, 0, 0);
        MaskGreyLevel = new QPushButton(layoutWidget);
        MaskGreyLevel->setObjectName(QString::fromUtf8("MaskGreyLevel"));
        MaskGreyLevel->setFont(font1);

        verticalLayout_2->addWidget(MaskGreyLevel);

        MaskImage = new QPushButton(layoutWidget);
        MaskImage->setObjectName(QString::fromUtf8("MaskImage"));
        MaskImage->setFont(font1);

        verticalLayout_2->addWidget(MaskImage);

        BinaryMaskDcm = new QPushButton(layoutWidget);
        BinaryMaskDcm->setObjectName(QString::fromUtf8("BinaryMaskDcm"));

        verticalLayout_2->addWidget(BinaryMaskDcm);

        layoutWidget1 = new QWidget(groupBox_3);
        layoutWidget1->setObjectName(QString::fromUtf8("layoutWidget1"));
        layoutWidget1->setGeometry(QRect(10, 20, 151, 83));
        verticalLayout = new QVBoxLayout(layoutWidget1);
        verticalLayout->setObjectName(QString::fromUtf8("verticalLayout"));
        verticalLayout->setContentsMargins(0, 0, 0, 0);
        ImageResample = new QPushButton(layoutWidget1);
        ImageResample->setObjectName(QString::fromUtf8("ImageResample"));
        ImageResample->setFont(font1);

        verticalLayout->addWidget(ImageResample);

        ItkToVtkToItk = new QPushButton(layoutWidget1);
        ItkToVtkToItk->setObjectName(QString::fromUtf8("ItkToVtkToItk"));
        ItkToVtkToItk->setFont(font1);

        verticalLayout->addWidget(ItkToVtkToItk);

        PseudoCalibration = new QPushButton(layoutWidget1);
        PseudoCalibration->setObjectName(QString::fromUtf8("PseudoCalibration"));

        verticalLayout->addWidget(PseudoCalibration);

        groupBox_8 = new QGroupBox(page_1);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(10, 120, 351, 201));
        groupBox_8->setFont(font1);
        FindReference = new QPushButton(groupBox_8);
        FindReference->setObjectName(QString::fromUtf8("FindReference"));
        FindReference->setGeometry(QRect(10, 20, 331, 23));
        groupBox_18 = new QGroupBox(groupBox_8);
        groupBox_18->setObjectName(QString::fromUtf8("groupBox_18"));
        groupBox_18->setGeometry(QRect(10, 140, 331, 51));
        SurfaceComparisonImage = new QPushButton(groupBox_18);
        SurfaceComparisonImage->setObjectName(QString::fromUtf8("SurfaceComparisonImage"));
        SurfaceComparisonImage->setGeometry(QRect(10, 20, 151, 23));
        SurfaceComparisonImage->setFont(font1);
        VolumeComparisonImage = new QPushButton(groupBox_18);
        VolumeComparisonImage->setObjectName(QString::fromUtf8("VolumeComparisonImage"));
        VolumeComparisonImage->setGeometry(QRect(170, 20, 151, 23));
        groupBox_19 = new QGroupBox(groupBox_8);
        groupBox_19->setObjectName(QString::fromUtf8("groupBox_19"));
        groupBox_19->setGeometry(QRect(10, 50, 331, 81));
        VfToDvf = new QPushButton(groupBox_19);
        VfToDvf->setObjectName(QString::fromUtf8("VfToDvf"));
        VfToDvf->setGeometry(QRect(10, 20, 141, 23));
        RecreateMoving = new QPushButton(groupBox_19);
        RecreateMoving->setObjectName(QString::fromUtf8("RecreateMoving"));
        RecreateMoving->setGeometry(QRect(180, 50, 141, 23));
        RecreateMoving->setFont(font1);
        VfToDvfInverted = new QPushButton(groupBox_19);
        VfToDvfInverted->setObjectName(QString::fromUtf8("VfToDvfInverted"));
        VfToDvfInverted->setGeometry(QRect(180, 20, 141, 23));
        line_2 = new QFrame(groupBox_19);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(156, 20, 20, 51));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        RecreateReference = new QPushButton(groupBox_19);
        RecreateReference->setObjectName(QString::fromUtf8("RecreateReference"));
        RecreateReference->setGeometry(QRect(10, 50, 141, 23));
        toolBox->addItem(page_1, QString::fromUtf8("IMAGE TOOL"));
        page_2 = new QWidget();
        page_2->setObjectName(QString::fromUtf8("page_2"));
        page_2->setGeometry(QRect(0, 0, 375, 617));
        groupBox_6 = new QGroupBox(page_2);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(10, 0, 351, 161));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Segoe UI"));
        font2.setPointSize(9);
        groupBox_6->setFont(font2);
        groupBox_11 = new QGroupBox(groupBox_6);
        groupBox_11->setObjectName(QString::fromUtf8("groupBox_11"));
        groupBox_11->setGeometry(QRect(10, 20, 211, 77));
        groupBox_11->setFont(font1);
        CreateMesh = new QPushButton(groupBox_11);
        CreateMesh->setObjectName(QString::fromUtf8("CreateMesh"));
        CreateMesh->setGeometry(QRect(10, 47, 81, 23));
        CreateMesh->setFont(font1);
        Simplify = new QDoubleSpinBox(groupBox_11);
        Simplify->setObjectName(QString::fromUtf8("Simplify"));
        Simplify->setGeometry(QRect(151, 20, 50, 19));
        Simplify->setFont(font1);
        Simplify->setLayoutDirection(Qt::LeftToRight);
        Simplify->setAlignment(Qt::AlignCenter);
        Simplify->setMaximum(1);
        Simplify->setSingleStep(0.1);
        Simplify->setValue(0.4);
        Smooth = new QSpinBox(groupBox_11);
        Smooth->setObjectName(QString::fromUtf8("Smooth"));
        Smooth->setGeometry(QRect(151, 47, 50, 19));
        Smooth->setFont(font1);
        Smooth->setLayoutDirection(Qt::LeftToRight);
        Smooth->setAlignment(Qt::AlignCenter);
        Smooth->setMaximum(1000);
        Smooth->setValue(150);
        label = new QLabel(groupBox_11);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(105, 47, 47, 21));
        label->setFont(font1);
        LoadImageMesh = new QPushButton(groupBox_11);
        LoadImageMesh->setObjectName(QString::fromUtf8("LoadImageMesh"));
        LoadImageMesh->setGeometry(QRect(10, 20, 81, 23));
        LoadImageMesh->setFont(font2);
        label_2 = new QLabel(groupBox_11);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(105, 20, 47, 21));
        label_2->setFont(font1);
        groupBox_13 = new QGroupBox(groupBox_6);
        groupBox_13->setObjectName(QString::fromUtf8("groupBox_13"));
        groupBox_13->setGeometry(QRect(240, 20, 100, 77));
        groupBox_13->setFont(font1);
        CreateVolumeMesh = new QPushButton(groupBox_13);
        CreateVolumeMesh->setObjectName(QString::fromUtf8("CreateVolumeMesh"));
        CreateVolumeMesh->setGeometry(QRect(10, 47, 81, 23));
        CreateVolumeMesh->setFont(font1);
        LoadSurfaceMesh = new QPushButton(groupBox_13);
        LoadSurfaceMesh->setObjectName(QString::fromUtf8("LoadSurfaceMesh"));
        LoadSurfaceMesh->setGeometry(QRect(10, 20, 81, 23));
        LoadSurfaceMesh->setFont(font1);
        groupBox_26 = new QGroupBox(groupBox_6);
        groupBox_26->setObjectName(QString::fromUtf8("groupBox_26"));
        groupBox_26->setGeometry(QRect(10, 100, 331, 53));
        groupBox_26->setFont(font2);
        layoutWidget2 = new QWidget(groupBox_26);
        layoutWidget2->setObjectName(QString::fromUtf8("layoutWidget2"));
        layoutWidget2->setGeometry(QRect(11, 21, 311, 25));
        horizontalLayout = new QHBoxLayout(layoutWidget2);
        horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        MeshJacobian = new QPushButton(layoutWidget2);
        MeshJacobian->setObjectName(QString::fromUtf8("MeshJacobian"));
        MeshJacobian->setFont(font2);

        horizontalLayout->addWidget(MeshJacobian);

        MeshEdgeRatio = new QPushButton(layoutWidget2);
        MeshEdgeRatio->setObjectName(QString::fromUtf8("MeshEdgeRatio"));
        MeshEdgeRatio->setFont(font2);

        horizontalLayout->addWidget(MeshEdgeRatio);

        MeshAngle = new QPushButton(layoutWidget2);
        MeshAngle->setObjectName(QString::fromUtf8("MeshAngle"));
        MeshAngle->setFont(font2);

        horizontalLayout->addWidget(MeshAngle);

        groupBox_7 = new QGroupBox(page_2);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(10, 170, 351, 131));
        groupBox_7->setFont(font2);
        groupBox_12 = new QGroupBox(groupBox_7);
        groupBox_12->setObjectName(QString::fromUtf8("groupBox_12"));
        groupBox_12->setGeometry(QRect(10, 20, 331, 51));
        groupBox_12->setFont(font2);
        CreateXml = new QPushButton(groupBox_12);
        CreateXml->setObjectName(QString::fromUtf8("CreateXml"));
        CreateXml->setGeometry(QRect(110, 20, 91, 23));
        CreateXml->setFont(font2);
        PickLandmarks = new QPushButton(groupBox_12);
        PickLandmarks->setObjectName(QString::fromUtf8("PickLandmarks"));
        PickLandmarks->setGeometry(QRect(10, 20, 91, 23));
        PickLandmarks->setFont(font2);
        CreateXmlFromFiles = new QPushButton(groupBox_12);
        CreateXmlFromFiles->setObjectName(QString::fromUtf8("CreateXmlFromFiles"));
        CreateXmlFromFiles->setGeometry(QRect(230, 20, 91, 23));
        CreateXmlFromFiles->setFont(font2);
        line = new QFrame(groupBox_12);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(206, 20, 20, 21));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        groupBox_27 = new QGroupBox(groupBox_7);
        groupBox_27->setObjectName(QString::fromUtf8("groupBox_27"));
        groupBox_27->setGeometry(QRect(10, 70, 101, 51));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Segoe UI"));
        font3.setPointSize(8);
        groupBox_27->setFont(font3);
        RunMorpher = new QPushButton(groupBox_27);
        RunMorpher->setObjectName(QString::fromUtf8("RunMorpher"));
        RunMorpher->setGeometry(QRect(10, 20, 81, 23));
        QFont font4;
        font4.setFamily(QString::fromUtf8("Segoe UI"));
        RunMorpher->setFont(font4);
        groupBox_14 = new QGroupBox(groupBox_7);
        groupBox_14->setObjectName(QString::fromUtf8("groupBox_14"));
        groupBox_14->setGeometry(QRect(130, 70, 211, 51));
        groupBox_14->setFont(font3);
        SurfaceValidation = new QPushButton(groupBox_14);
        SurfaceValidation->setObjectName(QString::fromUtf8("SurfaceValidation"));
        SurfaceValidation->setGeometry(QRect(10, 20, 91, 23));
        SurfaceValidation->setFont(font4);
        VolumeValidation = new QPushButton(groupBox_14);
        VolumeValidation->setObjectName(QString::fromUtf8("VolumeValidation"));
        VolumeValidation->setGeometry(QRect(110, 20, 91, 23));
        VolumeValidation->setFont(font4);
        groupBox_2 = new QGroupBox(page_2);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 310, 351, 301));
        groupBox_2->setFont(font2);
        groupBox_4 = new QGroupBox(groupBox_2);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(10, 100, 331, 71));
        groupBox_4->setFont(font1);
        CalculateMeshPCA = new QPushButton(groupBox_4);
        CalculateMeshPCA->setObjectName(QString::fromUtf8("CalculateMeshPCA"));
        CalculateMeshPCA->setGeometry(QRect(10, 40, 311, 23));
        CalculateMeshPCA->setFont(font1);
        ShapeMeshPCA = new QRadioButton(groupBox_4);
        ShapeMeshPCA->setObjectName(QString::fromUtf8("ShapeMeshPCA"));
        ShapeMeshPCA->setGeometry(QRect(11, 21, 83, 18));
        ShapeMeshPCA->setFont(font1);
        CombinedMeshPCA = new QRadioButton(groupBox_4);
        CombinedMeshPCA->setObjectName(QString::fromUtf8("CombinedMeshPCA"));
        CombinedMeshPCA->setGeometry(QRect(217, 21, 103, 18));
        CombinedMeshPCA->setFont(font1);
        IntensityMeshPCA = new QRadioButton(groupBox_4);
        IntensityMeshPCA->setObjectName(QString::fromUtf8("IntensityMeshPCA"));
        IntensityMeshPCA->setGeometry(QRect(114, 21, 97, 18));
        IntensityMeshPCA->setFont(font1);
        ShapeMeshPCA->raise();
        CombinedMeshPCA->raise();
        IntensityMeshPCA->raise();
        CalculateMeshPCA->raise();
        groupBox_24 = new QGroupBox(groupBox_2);
        groupBox_24->setObjectName(QString::fromUtf8("groupBox_24"));
        groupBox_24->setGeometry(QRect(10, 220, 331, 71));
        groupBox_24->setFont(font1);
        label_12 = new QLabel(groupBox_24);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 17, 80, 16));
        label_12->setFont(font1);
        NOfMeshInstances = new QSpinBox(groupBox_24);
        NOfMeshInstances->setObjectName(QString::fromUtf8("NOfMeshInstances"));
        NOfMeshInstances->setGeometry(QRect(100, 17, 50, 19));
        NOfMeshInstances->setFont(font1);
        NOfMeshInstances->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        NOfMeshInstances->setMaximum(1000);
        CreateMeshInstances = new QPushButton(groupBox_24);
        CreateMeshInstances->setObjectName(QString::fromUtf8("CreateMeshInstances"));
        CreateMeshInstances->setGeometry(QRect(10, 40, 309, 23));
        CreateMeshInstances->setFont(font1);
        label_13 = new QLabel(groupBox_24);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(200, 17, 66, 16));
        label_13->setFont(font1);
        NOfMeshModes = new QSpinBox(groupBox_24);
        NOfMeshModes->setObjectName(QString::fromUtf8("NOfMeshModes"));
        NOfMeshModes->setGeometry(QRect(270, 17, 51, 19));
        NOfMeshModes->setFont(font1);
        NOfMeshModes->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        NOfMeshModes->setMaximum(200);
        NOfMeshModes->setSingleStep(1);
        groupBox_9 = new QGroupBox(groupBox_2);
        groupBox_9->setObjectName(QString::fromUtf8("groupBox_9"));
        groupBox_9->setGeometry(QRect(10, 170, 331, 51));
        groupBox_9->setFont(font1);
        RecreateMeshInstance = new QPushButton(groupBox_9);
        RecreateMeshInstance->setObjectName(QString::fromUtf8("RecreateMeshInstance"));
        RecreateMeshInstance->setGeometry(QRect(10, 20, 301, 23));
        RecreateMeshInstance->setFont(font1);
        groupBox_25 = new QGroupBox(groupBox_2);
        groupBox_25->setObjectName(QString::fromUtf8("groupBox_25"));
        groupBox_25->setGeometry(QRect(10, 20, 331, 81));
        groupBox_25->setFont(font2);
        MeshAlignment = new QPushButton(groupBox_25);
        MeshAlignment->setObjectName(QString::fromUtf8("MeshAlignment"));
        MeshAlignment->setGeometry(QRect(10, 50, 311, 23));
        MeshAlignment->setFont(font4);
        ExtractCoordinatesAndIntensities = new QPushButton(groupBox_25);
        ExtractCoordinatesAndIntensities->setObjectName(QString::fromUtf8("ExtractCoordinatesAndIntensities"));
        ExtractCoordinatesAndIntensities->setGeometry(QRect(10, 20, 151, 23));
        ExtractCoordinatesAndIntensities->setFont(font4);
        ExtractNodesAndElements = new QPushButton(groupBox_25);
        ExtractNodesAndElements->setObjectName(QString::fromUtf8("ExtractNodesAndElements"));
        ExtractNodesAndElements->setGeometry(QRect(170, 20, 151, 23));
        ExtractNodesAndElements->setFont(font4);
        toolBox->addItem(page_2, QString::fromUtf8("MESH TOOL"));
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        page_3->setGeometry(QRect(0, 0, 375, 617));
        groupBox_16 = new QGroupBox(page_3);
        groupBox_16->setObjectName(QString::fromUtf8("groupBox_16"));
        groupBox_16->setGeometry(QRect(10, 0, 351, 151));
        groupBox_16->setFont(font1);
        LoadMesh = new QPushButton(groupBox_16);
        LoadMesh->setObjectName(QString::fromUtf8("LoadMesh"));
        LoadMesh->setGeometry(QRect(10, 20, 161, 23));
        LoadImageAssigner = new QPushButton(groupBox_16);
        LoadImageAssigner->setObjectName(QString::fromUtf8("LoadImageAssigner"));
        LoadImageAssigner->setGeometry(QRect(180, 20, 161, 23));
        label_4 = new QLabel(groupBox_16);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(10, 54, 121, 21));
        AssignmentLawFirst = new QDoubleSpinBox(groupBox_16);
        AssignmentLawFirst->setObjectName(QString::fromUtf8("AssignmentLawFirst"));
        AssignmentLawFirst->setGeometry(QRect(134, 54, 61, 21));
        AssignmentLawFirst->setAlignment(Qt::AlignCenter);
        AssignmentLawFirst->setDecimals(3);
        AssignmentLawFirst->setSingleStep(0.001);
        AssignmentLawFirst->setValue(6.85);
        label_6 = new QLabel(groupBox_16);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(210, 54, 36, 21));
        label_7 = new QLabel(groupBox_16);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(218, 63, 21, 16));
        QFont font5;
        font5.setPointSize(7);
        label_7->setFont(font5);
        AssignmentLawSecond = new QDoubleSpinBox(groupBox_16);
        AssignmentLawSecond->setObjectName(QString::fromUtf8("AssignmentLawSecond"));
        AssignmentLawSecond->setGeometry(QRect(251, 54, 54, 21));
        AssignmentLawSecond->setAlignment(Qt::AlignCenter);
        AssignmentLawSecond->setSingleStep(0.01);
        AssignmentLawSecond->setValue(1.49);
        Assign = new QPushButton(groupBox_16);
        Assign->setObjectName(QString::fromUtf8("Assign"));
        Assign->setGeometry(QRect(10, 120, 331, 23));
        label_3 = new QLabel(groupBox_16);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(199, 61, 16, 16));
        groupBox_20 = new QGroupBox(groupBox_16);
        groupBox_20->setObjectName(QString::fromUtf8("groupBox_20"));
        groupBox_20->setGeometry(QRect(10, 80, 161, 31));
        AssignToNodes = new QRadioButton(groupBox_20);
        AssignToNodes->setObjectName(QString::fromUtf8("AssignToNodes"));
        AssignToNodes->setGeometry(QRect(10, 8, 56, 16));
        AssignToElements = new QRadioButton(groupBox_20);
        AssignToElements->setObjectName(QString::fromUtf8("AssignToElements"));
        AssignToElements->setGeometry(QRect(80, 8, 79, 16));
        groupBox_21 = new QGroupBox(groupBox_16);
        groupBox_21->setObjectName(QString::fromUtf8("groupBox_21"));
        groupBox_21->setGeometry(QRect(180, 80, 161, 31));
        AbaqusMatProp = new QRadioButton(groupBox_21);
        AbaqusMatProp->setObjectName(QString::fromUtf8("AbaqusMatProp"));
        AbaqusMatProp->setGeometry(QRect(10, 8, 65, 16));
        TxtMatProp = new QRadioButton(groupBox_21);
        TxtMatProp->setObjectName(QString::fromUtf8("TxtMatProp"));
        TxtMatProp->setGeometry(QRect(90, 8, 70, 16));
        groupBox_5 = new QGroupBox(page_3);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(10, 160, 351, 141));
        groupBox_5->setFont(font1);
        groupBox_29 = new QGroupBox(groupBox_5);
        groupBox_29->setObjectName(QString::fromUtf8("groupBox_29"));
        groupBox_29->setGeometry(QRect(10, 80, 331, 51));
        Falling = new QPushButton(groupBox_29);
        Falling->setObjectName(QString::fromUtf8("Falling"));
        Falling->setGeometry(QRect(170, 20, 151, 23));
        Walking = new QPushButton(groupBox_29);
        Walking->setObjectName(QString::fromUtf8("Walking"));
        Walking->setGeometry(QRect(10, 20, 151, 23));
        groupBox_28 = new QGroupBox(groupBox_5);
        groupBox_28->setObjectName(QString::fromUtf8("groupBox_28"));
        groupBox_28->setGeometry(QRect(10, 20, 331, 51));
        line_3 = new QFrame(groupBox_28);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(206, 20, 20, 21));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        PickApplicationPoints = new QPushButton(groupBox_28);
        PickApplicationPoints->setObjectName(QString::fromUtf8("PickApplicationPoints"));
        PickApplicationPoints->setGeometry(QRect(10, 20, 91, 23));
        SaveApplicationPoints = new QPushButton(groupBox_28);
        SaveApplicationPoints->setObjectName(QString::fromUtf8("SaveApplicationPoints"));
        SaveApplicationPoints->setGeometry(QRect(110, 20, 91, 23));
        PropagateApplicationPoints = new QPushButton(groupBox_28);
        PropagateApplicationPoints->setObjectName(QString::fromUtf8("PropagateApplicationPoints"));
        PropagateApplicationPoints->setGeometry(QRect(230, 20, 91, 23));
        groupBox_10 = new QGroupBox(page_3);
        groupBox_10->setObjectName(QString::fromUtf8("groupBox_10"));
        groupBox_10->setGeometry(QRect(10, 310, 351, 91));
        groupBox_10->setFont(font1);
        RunSimulation = new QPushButton(groupBox_10);
        RunSimulation->setObjectName(QString::fromUtf8("RunSimulation"));
        RunSimulation->setGeometry(QRect(10, 60, 331, 23));
        line_4 = new QFrame(groupBox_10);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setGeometry(QRect(10, 44, 331, 16));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        CreateAbaqusInpFalling = new QPushButton(groupBox_10);
        CreateAbaqusInpFalling->setObjectName(QString::fromUtf8("CreateAbaqusInpFalling"));
        CreateAbaqusInpFalling->setGeometry(QRect(180, 20, 161, 23));
        CreateAbaqusInp = new QPushButton(groupBox_10);
        CreateAbaqusInp->setObjectName(QString::fromUtf8("CreateAbaqusInp"));
        CreateAbaqusInp->setGeometry(QRect(10, 20, 161, 23));
        groupBox_22 = new QGroupBox(page_3);
        groupBox_22->setObjectName(QString::fromUtf8("groupBox_22"));
        groupBox_22->setGeometry(QRect(10, 517, 351, 101));
        groupBox_22->setFont(font1);
        LoadBoneMesh = new QPushButton(groupBox_22);
        LoadBoneMesh->setObjectName(QString::fromUtf8("LoadBoneMesh"));
        LoadBoneMesh->setGeometry(QRect(10, 20, 161, 23));
        LoadImplantMesh = new QPushButton(groupBox_22);
        LoadImplantMesh->setObjectName(QString::fromUtf8("LoadImplantMesh"));
        LoadImplantMesh->setGeometry(QRect(180, 20, 161, 23));
        ComputeAndSave = new QPushButton(groupBox_22);
        ComputeAndSave->setObjectName(QString::fromUtf8("ComputeAndSave"));
        ComputeAndSave->setGeometry(QRect(10, 70, 331, 23));
        Proximal = new QRadioButton(groupBox_22);
        Proximal->setObjectName(QString::fromUtf8("Proximal"));
        Proximal->setGeometry(QRect(11, 47, 67, 18));
        Diaphyseal = new QRadioButton(groupBox_22);
        Diaphyseal->setObjectName(QString::fromUtf8("Diaphyseal"));
        Diaphyseal->setGeometry(QRect(130, 47, 78, 18));
        Distal = new QRadioButton(groupBox_22);
        Distal->setObjectName(QString::fromUtf8("Distal"));
        Distal->setGeometry(QRect(270, 47, 50, 18));
        groupBox_30 = new QGroupBox(page_3);
        groupBox_30->setObjectName(QString::fromUtf8("groupBox_30"));
        groupBox_30->setGeometry(QRect(10, 410, 351, 80));
        groupBox_30->setFont(font1);
        ExtractNeckIntensities = new QPushButton(groupBox_30);
        ExtractNeckIntensities->setObjectName(QString::fromUtf8("ExtractNeckIntensities"));
        ExtractNeckIntensities->setGeometry(QRect(10, 20, 161, 23));
        toolBox->addItem(page_3, QString::fromUtf8("FEM TOOL"));
        splitter->addWidget(toolBox);
        qvtkWidget = new QVTKWidget(splitter);
        qvtkWidget->setObjectName(QString::fromUtf8("qvtkWidget"));
        splitter->addWidget(qvtkWidget);

        gridLayout->addWidget(splitter, 0, 0, 1, 1);


        gridLayout_2->addWidget(groupBox_31, 0, 0, 1, 1);

        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1271, 21));
        menu_Rendering = new QMenu(menubar);
        menu_Rendering->setObjectName(QString::fromUtf8("menu_Rendering"));
        menuMesh = new QMenu(menu_Rendering);
        menuMesh->setObjectName(QString::fromUtf8("menuMesh"));
        menuSurface_mesh = new QMenu(menuMesh);
        menuSurface_mesh->setObjectName(QString::fromUtf8("menuSurface_mesh"));
        menuVolume_Mesh = new QMenu(menuMesh);
        menuVolume_Mesh->setObjectName(QString::fromUtf8("menuVolume_Mesh"));
        menuImage = new QMenu(menu_Rendering);
        menuImage->setObjectName(QString::fromUtf8("menuImage"));
        menuPoints_2 = new QMenu(menu_Rendering);
        menuPoints_2->setObjectName(QString::fromUtf8("menuPoints_2"));
        menuDifference = new QMenu(menu_Rendering);
        menuDifference->setObjectName(QString::fromUtf8("menuDifference"));
        menuEuclidean = new QMenu(menuDifference);
        menuEuclidean->setObjectName(QString::fromUtf8("menuEuclidean"));
        menu_Change_format = new QMenu(menubar);
        menu_Change_format->setObjectName(QString::fromUtf8("menu_Change_format"));
        menuImages = new QMenu(menu_Change_format);
        menuImages->setObjectName(QString::fromUtf8("menuImages"));
        menuMesh_2 = new QMenu(menu_Change_format);
        menuMesh_2->setObjectName(QString::fromUtf8("menuMesh_2"));
        menuVolume_Mesh_2 = new QMenu(menuMesh_2);
        menuVolume_Mesh_2->setObjectName(QString::fromUtf8("menuVolume_Mesh_2"));
        menuSurfaceMesh = new QMenu(menuMesh_2);
        menuSurfaceMesh->setObjectName(QString::fromUtf8("menuSurfaceMesh"));
        menuPoints = new QMenu(menu_Change_format);
        menuPoints->setObjectName(QString::fromUtf8("menuPoints"));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        menubar->addAction(menu_Rendering->menuAction());
        menubar->addAction(menu_Change_format->menuAction());
        menu_Rendering->addAction(menuImage->menuAction());
        menu_Rendering->addAction(menuMesh->menuAction());
        menu_Rendering->addAction(menuPoints_2->menuAction());
        menu_Rendering->addAction(RenderLine);
        menu_Rendering->addAction(RenderOBB);
        menu_Rendering->addAction(RenderCoordinateSystem);
        menu_Rendering->addSeparator();
        menu_Rendering->addAction(menuDifference->menuAction());
        menu_Rendering->addSeparator();
        menu_Rendering->addAction(DrawLineStart);
        menu_Rendering->addAction(DrawLineStop);
        menu_Rendering->addSeparator();
        menu_Rendering->addAction(ResetView);
        menuMesh->addAction(menuSurface_mesh->menuAction());
        menuMesh->addAction(menuVolume_Mesh->menuAction());
        menuMesh->addAction(RenderVtkPolyData);
        menuSurface_mesh->addAction(RenderStl);
        menuSurface_mesh->addAction(RenderSurfaceCdb);
        menuVolume_Mesh->addAction(RenderVolumeInpAbaqus);
        menuVolume_Mesh->addAction(RenderVolumeCdb);
        menuImage->addAction(RenderMetafile);
        menuPoints_2->addAction(RenderPointsXyz);
        menuPoints_2->addAction(RenderPointsXyzWithColorbar);
        menuPoints_2->addAction(RenderPointsXyzWithColorbarC);
        menuDifference->addAction(menuEuclidean->menuAction());
        menuEuclidean->addAction(EuclideanDistanceImage);
        menuEuclidean->addAction(EuclideanDistancePoints);
        menu_Change_format->addAction(menuImages->menuAction());
        menu_Change_format->addAction(menuMesh_2->menuAction());
        menu_Change_format->addAction(menuPoints->menuAction());
        menuImages->addAction(DcmToMhd);
        menuImages->addAction(MhdToDcm);
        menuImages->addAction(MhdToHdr);
        menuMesh_2->addAction(menuSurfaceMesh->menuAction());
        menuMesh_2->addAction(menuVolume_Mesh_2->menuAction());
        menuVolume_Mesh_2->addAction(AbaqusToCdb);
        menuVolume_Mesh_2->addAction(CdbToInpAbaqus);
        menuVolume_Mesh_2->addAction(MorpherVolumeCdbToVtk_2);
        menuSurfaceMesh->addAction(MorpherSurfaceCdbToStl_2);
        menuPoints->addAction(PointsStlToTxt);
        menuPoints->addAction(PointsVtkToTxt);
        menuPoints->addAction(PointsTxtMatrixToVector);

        retranslateUi(MainWindow);

        toolBox->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0, QApplication::UnicodeUTF8));
        DcmToMhd->setText(QApplication::translate("MainWindow", ".dcm to .mhd", 0, QApplication::UnicodeUTF8));
        MorpherVolumeCdbToVtk->setText(QApplication::translate("MainWindow", ".cdb to .vtk", 0, QApplication::UnicodeUTF8));
        PointsStlToTxt->setText(QApplication::translate("MainWindow", ".stl to .txt", 0, QApplication::UnicodeUTF8));
        MorpherVolumeCdbToVtk_2->setText(QApplication::translate("MainWindow", ".cdb to .vtk", 0, QApplication::UnicodeUTF8));
        MorpherSurfaceCdbToStl_2->setText(QApplication::translate("MainWindow", ".cdb to.stl", 0, QApplication::UnicodeUTF8));
        RenderStl->setText(QApplication::translate("MainWindow", ".stl", 0, QApplication::UnicodeUTF8));
        RenderVolumeCdb->setText(QApplication::translate("MainWindow", ".cdb", 0, QApplication::UnicodeUTF8));
        RenderMetafile->setText(QApplication::translate("MainWindow", "metafile", 0, QApplication::UnicodeUTF8));
        InpToCdb->setText(QApplication::translate("MainWindow", ".inp(neutral) to .cdb", 0, QApplication::UnicodeUTF8));
        RenderSurfaceCdb->setText(QApplication::translate("MainWindow", ".cdb", 0, QApplication::UnicodeUTF8));
        RenderVolumeVtk->setText(QApplication::translate("MainWindow", ".vtk", 0, QApplication::UnicodeUTF8));
        RenderSurfaceVtk->setText(QApplication::translate("MainWindow", ".vtk", 0, QApplication::UnicodeUTF8));
        PointsVtkToTxt->setText(QApplication::translate("MainWindow", ".vtk to .txt", 0, QApplication::UnicodeUTF8));
        MhdToHdr->setText(QApplication::translate("MainWindow", ".mhd to .hdr", 0, QApplication::UnicodeUTF8));
        CdbToInpAbaqus->setText(QApplication::translate("MainWindow", ".cdb to .inp", 0, QApplication::UnicodeUTF8));
        RenderVolumeInpAbaqus->setText(QApplication::translate("MainWindow", ".inp", 0, QApplication::UnicodeUTF8));
        PointsTxtMatrixToVector->setText(QApplication::translate("MainWindow", ".txt (Nx3) to .txt (3Nx1)", 0, QApplication::UnicodeUTF8));
        ResetView->setText(QApplication::translate("MainWindow", "Reset view", 0, QApplication::UnicodeUTF8));
        RenderCoordinateSystem->setText(QApplication::translate("MainWindow", "Coordinate System", 0, QApplication::UnicodeUTF8));
        MhdToDcm->setText(QApplication::translate("MainWindow", ".mhd to .dcm", 0, QApplication::UnicodeUTF8));
        AbaqusToCdb->setText(QApplication::translate("MainWindow", ".inp to .cdb", 0, QApplication::UnicodeUTF8));
        RenderVtkPolyData->setText(QApplication::translate("MainWindow", "VtkPolyData", 0, QApplication::UnicodeUTF8));
        RenderOBB->setText(QApplication::translate("MainWindow", "OBB", 0, QApplication::UnicodeUTF8));
        RenderPointsXyz->setText(QApplication::translate("MainWindow", "x,y,z", 0, QApplication::UnicodeUTF8));
        RenderPointsXyzWithColorbar->setText(QApplication::translate("MainWindow", "x,y,z with colorbar B/W", 0, QApplication::UnicodeUTF8));
        DistancePoints->setText(QApplication::translate("MainWindow", "Points", 0, QApplication::UnicodeUTF8));
        EuclideanDistanceImage->setText(QApplication::translate("MainWindow", "Images", 0, QApplication::UnicodeUTF8));
        EuclideanDistancePoints->setText(QApplication::translate("MainWindow", "Points", 0, QApplication::UnicodeUTF8));
        RenderPointsXyzWithColorbarC->setText(QApplication::translate("MainWindow", "x,y,z with colorbar C", 0, QApplication::UnicodeUTF8));
        DrawLineStart->setText(QApplication::translate("MainWindow", "Draw line start", 0, QApplication::UnicodeUTF8));
        DrawLineStop->setText(QApplication::translate("MainWindow", "Draw line stop", 0, QApplication::UnicodeUTF8));
        RenderLine->setText(QApplication::translate("MainWindow", "Line", 0, QApplication::UnicodeUTF8));
        groupBox_31->setTitle(QString());
#ifndef QT_NO_TOOLTIP
        toolBox->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        groupBox->setTitle(QApplication::translate("MainWindow", "STATISTICAL MODEL", 0, QApplication::UnicodeUTF8));
        groupBox_15->setTitle(QApplication::translate("MainWindow", "validation", 0, QApplication::UnicodeUTF8));
        RecreateImageInstance->setText(QApplication::translate("MainWindow", "recreate instance", 0, QApplication::UnicodeUTF8));
        groupBox_17->setTitle(QApplication::translate("MainWindow", "calculation", 0, QApplication::UnicodeUTF8));
        ShapeImagePCA->setText(QApplication::translate("MainWindow", "Shape PCA", 0, QApplication::UnicodeUTF8));
        CombinedImagePCA->setText(QApplication::translate("MainWindow", "Combined PCA", 0, QApplication::UnicodeUTF8));
        IntensityImagePCA->setText(QApplication::translate("MainWindow", "Intensity PCA", 0, QApplication::UnicodeUTF8));
        CalculateImagePCA->setText(QApplication::translate("MainWindow", "calculate", 0, QApplication::UnicodeUTF8));
        groupBox_23->setTitle(QApplication::translate("MainWindow", "new instances", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("MainWindow", "n. of instances", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("MainWindow", "n. of modes", 0, QApplication::UnicodeUTF8));
        CreateImageInstances->setText(QApplication::translate("MainWindow", "create instances", 0, QApplication::UnicodeUTF8));
        groupBox_3->setTitle(QApplication::translate("MainWindow", "IMAGE PREPROCESSING", 0, QApplication::UnicodeUTF8));
        MaskGreyLevel->setText(QApplication::translate("MainWindow", "maskGreyLevel", 0, QApplication::UnicodeUTF8));
        MaskImage->setText(QApplication::translate("MainWindow", "mask image", 0, QApplication::UnicodeUTF8));
        BinaryMaskDcm->setText(QApplication::translate("MainWindow", "binary mask image .dcm", 0, QApplication::UnicodeUTF8));
        ImageResample->setText(QApplication::translate("MainWindow", "resample", 0, QApplication::UnicodeUTF8));
        ItkToVtkToItk->setText(QApplication::translate("MainWindow", "itk to vtk to itk", 0, QApplication::UnicodeUTF8));
        PseudoCalibration->setText(QApplication::translate("MainWindow", "pseudo calibration", 0, QApplication::UnicodeUTF8));
        groupBox_8->setTitle(QApplication::translate("MainWindow", "CORRESPONDENCES - REGISTRATION", 0, QApplication::UnicodeUTF8));
        FindReference->setText(QApplication::translate("MainWindow", "find reference", 0, QApplication::UnicodeUTF8));
        groupBox_18->setTitle(QApplication::translate("MainWindow", "validation", 0, QApplication::UnicodeUTF8));
        SurfaceComparisonImage->setText(QApplication::translate("MainWindow", "surface comparison", 0, QApplication::UnicodeUTF8));
        VolumeComparisonImage->setText(QApplication::translate("MainWindow", "volume comparison", 0, QApplication::UnicodeUTF8));
        groupBox_19->setTitle(QApplication::translate("MainWindow", "warping", 0, QApplication::UnicodeUTF8));
        VfToDvf->setText(QApplication::translate("MainWindow", "vf to dvf", 0, QApplication::UnicodeUTF8));
        RecreateMoving->setText(QApplication::translate("MainWindow", "recreate moving", 0, QApplication::UnicodeUTF8));
        VfToDvfInverted->setText(QApplication::translate("MainWindow", "vf to dvf (-1)", 0, QApplication::UnicodeUTF8));
        RecreateReference->setText(QApplication::translate("MainWindow", "recreate reference", 0, QApplication::UnicodeUTF8));
        toolBox->setItemText(toolBox->indexOf(page_1), QApplication::translate("MainWindow", "IMAGE TOOL", 0, QApplication::UnicodeUTF8));
        groupBox_6->setTitle(QApplication::translate("MainWindow", "MESH CREATION", 0, QApplication::UnicodeUTF8));
        groupBox_11->setTitle(QApplication::translate("MainWindow", "surface mesh", 0, QApplication::UnicodeUTF8));
        CreateMesh->setText(QApplication::translate("MainWindow", "create", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("MainWindow", "smooth", 0, QApplication::UnicodeUTF8));
        LoadImageMesh->setText(QApplication::translate("MainWindow", "load", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("MainWindow", "simplify", 0, QApplication::UnicodeUTF8));
        groupBox_13->setTitle(QApplication::translate("MainWindow", "volume mesh", 0, QApplication::UnicodeUTF8));
        CreateVolumeMesh->setText(QApplication::translate("MainWindow", "create", 0, QApplication::UnicodeUTF8));
        LoadSurfaceMesh->setText(QApplication::translate("MainWindow", "load", 0, QApplication::UnicodeUTF8));
        groupBox_26->setTitle(QApplication::translate("MainWindow", "volume mesh quality", 0, QApplication::UnicodeUTF8));
        MeshJacobian->setText(QApplication::translate("MainWindow", "jacobian", 0, QApplication::UnicodeUTF8));
        MeshEdgeRatio->setText(QApplication::translate("MainWindow", "edge ratio", 0, QApplication::UnicodeUTF8));
        MeshAngle->setText(QApplication::translate("MainWindow", "min angle", 0, QApplication::UnicodeUTF8));
        groupBox_7->setTitle(QApplication::translate("MainWindow", "CORRESPONDENCES - MESH MORPHER", 0, QApplication::UnicodeUTF8));
        groupBox_12->setTitle(QApplication::translate("MainWindow", "preprocessing", 0, QApplication::UnicodeUTF8));
        CreateXml->setText(QApplication::translate("MainWindow", "create .xml", 0, QApplication::UnicodeUTF8));
        PickLandmarks->setText(QApplication::translate("MainWindow", "pick landmarks", 0, QApplication::UnicodeUTF8));
        CreateXmlFromFiles->setText(QApplication::translate("MainWindow", ".xml from files", 0, QApplication::UnicodeUTF8));
        groupBox_27->setTitle(QApplication::translate("MainWindow", "morphing", 0, QApplication::UnicodeUTF8));
        RunMorpher->setText(QApplication::translate("MainWindow", "run morpher", 0, QApplication::UnicodeUTF8));
        groupBox_14->setTitle(QApplication::translate("MainWindow", "validation", 0, QApplication::UnicodeUTF8));
        SurfaceValidation->setText(QApplication::translate("MainWindow", "surface", 0, QApplication::UnicodeUTF8));
        VolumeValidation->setText(QApplication::translate("MainWindow", "volume", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "STATISTICAL  MODEL", 0, QApplication::UnicodeUTF8));
        groupBox_4->setTitle(QApplication::translate("MainWindow", "calculation", 0, QApplication::UnicodeUTF8));
        CalculateMeshPCA->setText(QApplication::translate("MainWindow", "calculate", 0, QApplication::UnicodeUTF8));
        ShapeMeshPCA->setText(QApplication::translate("MainWindow", "Shape PCA", 0, QApplication::UnicodeUTF8));
        CombinedMeshPCA->setText(QApplication::translate("MainWindow", "Combined PCA", 0, QApplication::UnicodeUTF8));
        IntensityMeshPCA->setText(QApplication::translate("MainWindow", "Intensity PCA", 0, QApplication::UnicodeUTF8));
        groupBox_24->setTitle(QApplication::translate("MainWindow", "new instances", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("MainWindow", "n. of instances", 0, QApplication::UnicodeUTF8));
        CreateMeshInstances->setText(QApplication::translate("MainWindow", "create instances", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("MainWindow", "n. of modes", 0, QApplication::UnicodeUTF8));
        groupBox_9->setTitle(QApplication::translate("MainWindow", "validation", 0, QApplication::UnicodeUTF8));
        RecreateMeshInstance->setText(QApplication::translate("MainWindow", "recreate instance", 0, QApplication::UnicodeUTF8));
        groupBox_25->setTitle(QApplication::translate("MainWindow", "preprocessing", 0, QApplication::UnicodeUTF8));
        MeshAlignment->setText(QApplication::translate("MainWindow", "mesh alignment", 0, QApplication::UnicodeUTF8));
        ExtractCoordinatesAndIntensities->setText(QApplication::translate("MainWindow", "extract coords and ints", 0, QApplication::UnicodeUTF8));
        ExtractNodesAndElements->setText(QApplication::translate("MainWindow", "extract nodes and elems", 0, QApplication::UnicodeUTF8));
        toolBox->setItemText(toolBox->indexOf(page_2), QApplication::translate("MainWindow", "MESH TOOL", 0, QApplication::UnicodeUTF8));
        groupBox_16->setTitle(QApplication::translate("MainWindow", "MATERIAL  PROPERTIES", 0, QApplication::UnicodeUTF8));
        LoadMesh->setText(QApplication::translate("MainWindow", "load mesh", 0, QApplication::UnicodeUTF8));
        LoadImageAssigner->setText(QApplication::translate("MainWindow", "load image", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("MainWindow", "assignment law:   E =", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("MainWindow", "\317\201     ^", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("MainWindow", "app", 0, QApplication::UnicodeUTF8));
        Assign->setText(QApplication::translate("MainWindow", "assign and save", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("MainWindow", "*", 0, QApplication::UnicodeUTF8));
        groupBox_20->setTitle(QString());
        AssignToNodes->setText(QApplication::translate("MainWindow", "nodes", 0, QApplication::UnicodeUTF8));
        AssignToElements->setText(QApplication::translate("MainWindow", "elements", 0, QApplication::UnicodeUTF8));
        groupBox_21->setTitle(QString());
        AbaqusMatProp->setText(QApplication::translate("MainWindow", "abaqus ", 0, QApplication::UnicodeUTF8));
        TxtMatProp->setText(QApplication::translate("MainWindow", ".txt", 0, QApplication::UnicodeUTF8));
        groupBox_5->setTitle(QApplication::translate("MainWindow", "BOUNDARY CONDITIONS", 0, QApplication::UnicodeUTF8));
        groupBox_29->setTitle(QApplication::translate("MainWindow", "load type", 0, QApplication::UnicodeUTF8));
        Falling->setText(QApplication::translate("MainWindow", "sideways fall", 0, QApplication::UnicodeUTF8));
        Walking->setText(QApplication::translate("MainWindow", "one leg stance", 0, QApplication::UnicodeUTF8));
        groupBox_28->setTitle(QApplication::translate("MainWindow", "application points", 0, QApplication::UnicodeUTF8));
        PickApplicationPoints->setText(QApplication::translate("MainWindow", "pick", 0, QApplication::UnicodeUTF8));
        SaveApplicationPoints->setText(QApplication::translate("MainWindow", "save", 0, QApplication::UnicodeUTF8));
        PropagateApplicationPoints->setText(QApplication::translate("MainWindow", "propagate", 0, QApplication::UnicodeUTF8));
        groupBox_10->setTitle(QApplication::translate("MainWindow", "FINITE ELEMENT SIMULATION", 0, QApplication::UnicodeUTF8));
        RunSimulation->setText(QApplication::translate("MainWindow", "run simulation", 0, QApplication::UnicodeUTF8));
        CreateAbaqusInpFalling->setText(QApplication::translate("MainWindow", "abaqus .inp fall", 0, QApplication::UnicodeUTF8));
        CreateAbaqusInp->setText(QApplication::translate("MainWindow", "abaqus .inp stance", 0, QApplication::UnicodeUTF8));
        groupBox_22->setTitle(QApplication::translate("MainWindow", "IMPLANT FITTING", 0, QApplication::UnicodeUTF8));
        LoadBoneMesh->setText(QApplication::translate("MainWindow", "load bone mesh", 0, QApplication::UnicodeUTF8));
        LoadImplantMesh->setText(QApplication::translate("MainWindow", "load implant mesh", 0, QApplication::UnicodeUTF8));
        ComputeAndSave->setText(QApplication::translate("MainWindow", "compute and save", 0, QApplication::UnicodeUTF8));
        Proximal->setText(QApplication::translate("MainWindow", "proximal", 0, QApplication::UnicodeUTF8));
        Diaphyseal->setText(QApplication::translate("MainWindow", "diaphyseal", 0, QApplication::UnicodeUTF8));
        Distal->setText(QApplication::translate("MainWindow", "distal", 0, QApplication::UnicodeUTF8));
        groupBox_30->setTitle(QApplication::translate("MainWindow", "POSTPROCESSING", 0, QApplication::UnicodeUTF8));
        ExtractNeckIntensities->setText(QApplication::translate("MainWindow", "extract neck intensities", 0, QApplication::UnicodeUTF8));
        toolBox->setItemText(toolBox->indexOf(page_3), QApplication::translate("MainWindow", "FEM TOOL", 0, QApplication::UnicodeUTF8));
        menu_Rendering->setTitle(QApplication::translate("MainWindow", "&Rendering", 0, QApplication::UnicodeUTF8));
        menuMesh->setTitle(QApplication::translate("MainWindow", "Mesh", 0, QApplication::UnicodeUTF8));
        menuSurface_mesh->setTitle(QApplication::translate("MainWindow", "Surface Mesh", 0, QApplication::UnicodeUTF8));
        menuVolume_Mesh->setTitle(QApplication::translate("MainWindow", "Volume Mesh", 0, QApplication::UnicodeUTF8));
        menuImage->setTitle(QApplication::translate("MainWindow", "Image", 0, QApplication::UnicodeUTF8));
        menuPoints_2->setTitle(QApplication::translate("MainWindow", "Points", 0, QApplication::UnicodeUTF8));
        menuDifference->setTitle(QApplication::translate("MainWindow", "Distance", 0, QApplication::UnicodeUTF8));
        menuEuclidean->setTitle(QApplication::translate("MainWindow", "Euclidean", 0, QApplication::UnicodeUTF8));
        menu_Change_format->setTitle(QApplication::translate("MainWindow", "&Change format", 0, QApplication::UnicodeUTF8));
        menuImages->setTitle(QApplication::translate("MainWindow", "Images", 0, QApplication::UnicodeUTF8));
        menuMesh_2->setTitle(QApplication::translate("MainWindow", "Mesh", 0, QApplication::UnicodeUTF8));
        menuVolume_Mesh_2->setTitle(QApplication::translate("MainWindow", "Volume Mesh", 0, QApplication::UnicodeUTF8));
        menuSurfaceMesh->setTitle(QApplication::translate("MainWindow", "Surface Mesh", 0, QApplication::UnicodeUTF8));
        menuPoints->setTitle(QApplication::translate("MainWindow", "Points", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
